language: python
python:
  - "2.7"
install: "pip install -r requirements.txt --allow-external pypdf "
env:
  - DJANGO=1.5 DJANGO_SETTINGS_MODULE=vikalp.local_settings EMAIL_PASSWORD='!abcd1234'
script:
  - python manage.py test vikalp
